// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.2
// source: api/inflow/v1/inflow.proto

package v1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 时间序列数据点
type TimeSeriesDataPoint struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Time          *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=time,proto3" json:"time,omitempty"`     // 时间点
	Value         float64                `protobuf:"fixed64,2,opt,name=value,proto3" json:"value,omitempty"` // 值 (例如: 降雨量 mm)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TimeSeriesDataPoint) Reset() {
	*x = TimeSeriesDataPoint{}
	mi := &file_api_inflow_v1_inflow_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TimeSeriesDataPoint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TimeSeriesDataPoint) ProtoMessage() {}

func (x *TimeSeriesDataPoint) ProtoReflect() protoreflect.Message {
	mi := &file_api_inflow_v1_inflow_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TimeSeriesDataPoint.ProtoReflect.Descriptor instead.
func (*TimeSeriesDataPoint) Descriptor() ([]byte, []int) {
	return file_api_inflow_v1_inflow_proto_rawDescGZIP(), []int{0}
}

func (x *TimeSeriesDataPoint) GetTime() *timestamppb.Timestamp {
	if x != nil {
		return x.Time
	}
	return nil
}

func (x *TimeSeriesDataPoint) GetValue() float64 {
	if x != nil {
		return x.Value
	}
	return 0
}

// 流量过程线数据点
type HydrographDataPoint struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Time          *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=time,proto3" json:"time,omitempty"`                           // 时间点
	FlowRate      float64                `protobuf:"fixed64,2,opt,name=flow_rate,json=flowRate,proto3" json:"flow_rate,omitempty"` // 流量 (单位: m³/s)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HydrographDataPoint) Reset() {
	*x = HydrographDataPoint{}
	mi := &file_api_inflow_v1_inflow_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HydrographDataPoint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HydrographDataPoint) ProtoMessage() {}

func (x *HydrographDataPoint) ProtoReflect() protoreflect.Message {
	mi := &file_api_inflow_v1_inflow_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HydrographDataPoint.ProtoReflect.Descriptor instead.
func (*HydrographDataPoint) Descriptor() ([]byte, []int) {
	return file_api_inflow_v1_inflow_proto_rawDescGZIP(), []int{1}
}

func (x *HydrographDataPoint) GetTime() *timestamppb.Timestamp {
	if x != nil {
		return x.Time
	}
	return nil
}

func (x *HydrographDataPoint) GetFlowRate() float64 {
	if x != nil {
		return x.FlowRate
	}
	return 0
}

// --- 模拟降雨 ---
type SimulateRainfallRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	RainPatternType string                 `protobuf:"bytes,1,opt,name=rain_pattern_type,json=rainPatternType,proto3" json:"rain_pattern_type,omitempty"` // 雨型 (例如 "heavy_burst", "moderate_prolonged", "light_drizzle")
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *SimulateRainfallRequest) Reset() {
	*x = SimulateRainfallRequest{}
	mi := &file_api_inflow_v1_inflow_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SimulateRainfallRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SimulateRainfallRequest) ProtoMessage() {}

func (x *SimulateRainfallRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_inflow_v1_inflow_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SimulateRainfallRequest.ProtoReflect.Descriptor instead.
func (*SimulateRainfallRequest) Descriptor() ([]byte, []int) {
	return file_api_inflow_v1_inflow_proto_rawDescGZIP(), []int{2}
}

func (x *SimulateRainfallRequest) GetRainPatternType() string {
	if x != nil {
		return x.RainPatternType
	}
	return ""
}

type SimulateRainfallReply struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Past_24HRainfall []*TimeSeriesDataPoint `protobuf:"bytes,1,rep,name=past_24h_rainfall,json=past24hRainfall,proto3" json:"past_24h_rainfall,omitempty"` // 过去24小时模拟降雨 (按小时)
	Past_15DRainfall []*TimeSeriesDataPoint `protobuf:"bytes,2,rep,name=past_15d_rainfall,json=past15dRainfall,proto3" json:"past_15d_rainfall,omitempty"` // 过去15天模拟降雨 (按天)
	Message          string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *SimulateRainfallReply) Reset() {
	*x = SimulateRainfallReply{}
	mi := &file_api_inflow_v1_inflow_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SimulateRainfallReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SimulateRainfallReply) ProtoMessage() {}

func (x *SimulateRainfallReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_inflow_v1_inflow_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SimulateRainfallReply.ProtoReflect.Descriptor instead.
func (*SimulateRainfallReply) Descriptor() ([]byte, []int) {
	return file_api_inflow_v1_inflow_proto_rawDescGZIP(), []int{3}
}

func (x *SimulateRainfallReply) GetPast_24HRainfall() []*TimeSeriesDataPoint {
	if x != nil {
		return x.Past_24HRainfall
	}
	return nil
}

func (x *SimulateRainfallReply) GetPast_15DRainfall() []*TimeSeriesDataPoint {
	if x != nil {
		return x.Past_15DRainfall
	}
	return nil
}

func (x *SimulateRainfallReply) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// --- 预测降雨 ---
type PredictRainfallRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 将模拟的历史数据传给后端用于预测
	Past_24HRainfall []*TimeSeriesDataPoint `protobuf:"bytes,1,rep,name=past_24h_rainfall,json=past24hRainfall,proto3" json:"past_24h_rainfall,omitempty"` // repeated TimeSeriesDataPoint past_15d_rainfall = 2; // 看预测逻辑是否需要
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *PredictRainfallRequest) Reset() {
	*x = PredictRainfallRequest{}
	mi := &file_api_inflow_v1_inflow_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PredictRainfallRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PredictRainfallRequest) ProtoMessage() {}

func (x *PredictRainfallRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_inflow_v1_inflow_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PredictRainfallRequest.ProtoReflect.Descriptor instead.
func (*PredictRainfallRequest) Descriptor() ([]byte, []int) {
	return file_api_inflow_v1_inflow_proto_rawDescGZIP(), []int{4}
}

func (x *PredictRainfallRequest) GetPast_24HRainfall() []*TimeSeriesDataPoint {
	if x != nil {
		return x.Past_24HRainfall
	}
	return nil
}

type PredictRainfallReply struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Next_72HRainfall []*TimeSeriesDataPoint `protobuf:"bytes,1,rep,name=next_72h_rainfall,json=next72hRainfall,proto3" json:"next_72h_rainfall,omitempty"` // 未来72小时预测降雨 (按小时或按天，取决于后端实现)
	Message          string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *PredictRainfallReply) Reset() {
	*x = PredictRainfallReply{}
	mi := &file_api_inflow_v1_inflow_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PredictRainfallReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PredictRainfallReply) ProtoMessage() {}

func (x *PredictRainfallReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_inflow_v1_inflow_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PredictRainfallReply.ProtoReflect.Descriptor instead.
func (*PredictRainfallReply) Descriptor() ([]byte, []int) {
	return file_api_inflow_v1_inflow_proto_rawDescGZIP(), []int{5}
}

func (x *PredictRainfallReply) GetNext_72HRainfall() []*TimeSeriesDataPoint {
	if x != nil {
		return x.Next_72HRainfall
	}
	return nil
}

func (x *PredictRainfallReply) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// --- 计算入库洪量 ---
type CalculateInflowVolumeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BasinId       string                 `protobuf:"bytes,1,opt,name=basin_id,json=basinId,proto3" json:"basin_id,omitempty"`                // 流域ID (虽然目前只有一个，但加上更规范)
	RainfallData  []*TimeSeriesDataPoint `protobuf:"bytes,2,rep,name=rainfall_data,json=rainfallData,proto3" json:"rainfall_data,omitempty"` // 完整的降雨数据 (模拟+预测)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CalculateInflowVolumeRequest) Reset() {
	*x = CalculateInflowVolumeRequest{}
	mi := &file_api_inflow_v1_inflow_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CalculateInflowVolumeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CalculateInflowVolumeRequest) ProtoMessage() {}

func (x *CalculateInflowVolumeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_inflow_v1_inflow_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CalculateInflowVolumeRequest.ProtoReflect.Descriptor instead.
func (*CalculateInflowVolumeRequest) Descriptor() ([]byte, []int) {
	return file_api_inflow_v1_inflow_proto_rawDescGZIP(), []int{6}
}

func (x *CalculateInflowVolumeRequest) GetBasinId() string {
	if x != nil {
		return x.BasinId
	}
	return ""
}

func (x *CalculateInflowVolumeRequest) GetRainfallData() []*TimeSeriesDataPoint {
	if x != nil {
		return x.RainfallData
	}
	return nil
}

type CalculateInflowVolumeReply struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	TotalInflowVolume float64                `protobuf:"fixed64,1,opt,name=total_inflow_volume,json=totalInflowVolume,proto3" json:"total_inflow_volume,omitempty"` // 计算出的总入库洪量 (单位: 万立方米)
	Message           string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	HydrographData    []*HydrographDataPoint `protobuf:"bytes,4,rep,name=hydrograph_data,json=hydrographData,proto3" json:"hydrograph_data,omitempty"` // <--- 新增：入库流量过程线数据
	PeakFlow          float64                `protobuf:"fixed64,5,opt,name=peak_flow,json=peakFlow,proto3" json:"peak_flow,omitempty"`                 // <--- 新增：洪峰流量 (m³/s)
	PeakFlowTime      *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=peak_flow_time,json=peakFlowTime,proto3" json:"peak_flow_time,omitempty"`     // <--- 新增：洪峰时间
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *CalculateInflowVolumeReply) Reset() {
	*x = CalculateInflowVolumeReply{}
	mi := &file_api_inflow_v1_inflow_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CalculateInflowVolumeReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CalculateInflowVolumeReply) ProtoMessage() {}

func (x *CalculateInflowVolumeReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_inflow_v1_inflow_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CalculateInflowVolumeReply.ProtoReflect.Descriptor instead.
func (*CalculateInflowVolumeReply) Descriptor() ([]byte, []int) {
	return file_api_inflow_v1_inflow_proto_rawDescGZIP(), []int{7}
}

func (x *CalculateInflowVolumeReply) GetTotalInflowVolume() float64 {
	if x != nil {
		return x.TotalInflowVolume
	}
	return 0
}

func (x *CalculateInflowVolumeReply) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *CalculateInflowVolumeReply) GetHydrographData() []*HydrographDataPoint {
	if x != nil {
		return x.HydrographData
	}
	return nil
}

func (x *CalculateInflowVolumeReply) GetPeakFlow() float64 {
	if x != nil {
		return x.PeakFlow
	}
	return 0
}

func (x *CalculateInflowVolumeReply) GetPeakFlowTime() *timestamppb.Timestamp {
	if x != nil {
		return x.PeakFlowTime
	}
	return nil
}

var File_api_inflow_v1_inflow_proto protoreflect.FileDescriptor

const file_api_inflow_v1_inflow_proto_rawDesc = "" +
	"\n" +
	"\x1aapi/inflow/v1/inflow.proto\x12\tinflow.v1\x1a\x1cgoogle/api/annotations.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"[\n" +
	"\x13TimeSeriesDataPoint\x12.\n" +
	"\x04time\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\x04time\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x01R\x05value\"b\n" +
	"\x13HydrographDataPoint\x12.\n" +
	"\x04time\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\x04time\x12\x1b\n" +
	"\tflow_rate\x18\x02 \x01(\x01R\bflowRate\"E\n" +
	"\x17SimulateRainfallRequest\x12*\n" +
	"\x11rain_pattern_type\x18\x01 \x01(\tR\x0frainPatternType\"\xc9\x01\n" +
	"\x15SimulateRainfallReply\x12J\n" +
	"\x11past_24h_rainfall\x18\x01 \x03(\v2\x1e.inflow.v1.TimeSeriesDataPointR\x0fpast24hRainfall\x12J\n" +
	"\x11past_15d_rainfall\x18\x02 \x03(\v2\x1e.inflow.v1.TimeSeriesDataPointR\x0fpast15dRainfall\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\"d\n" +
	"\x16PredictRainfallRequest\x12J\n" +
	"\x11past_24h_rainfall\x18\x01 \x03(\v2\x1e.inflow.v1.TimeSeriesDataPointR\x0fpast24hRainfall\"|\n" +
	"\x14PredictRainfallReply\x12J\n" +
	"\x11next_72h_rainfall\x18\x01 \x03(\v2\x1e.inflow.v1.TimeSeriesDataPointR\x0fnext72hRainfall\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"~\n" +
	"\x1cCalculateInflowVolumeRequest\x12\x19\n" +
	"\bbasin_id\x18\x01 \x01(\tR\abasinId\x12C\n" +
	"\rrainfall_data\x18\x02 \x03(\v2\x1e.inflow.v1.TimeSeriesDataPointR\frainfallData\"\x8e\x02\n" +
	"\x1aCalculateInflowVolumeReply\x12.\n" +
	"\x13total_inflow_volume\x18\x01 \x01(\x01R\x11totalInflowVolume\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\x12G\n" +
	"\x0fhydrograph_data\x18\x04 \x03(\v2\x1e.inflow.v1.HydrographDataPointR\x0ehydrographData\x12\x1b\n" +
	"\tpeak_flow\x18\x05 \x01(\x01R\bpeakFlow\x12@\n" +
	"\x0epeak_flow_time\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\fpeakFlowTime2\xa4\x03\n" +
	"\rInflowService\x12\x81\x01\n" +
	"\x10SimulateRainfall\x12\".inflow.v1.SimulateRainfallRequest\x1a .inflow.v1.SimulateRainfallReply\"'\x82\xd3\xe4\x93\x02!:\x01*\"\x1c/v1/inflow/simulate-rainfall\x12}\n" +
	"\x0fPredictRainfall\x12!.inflow.v1.PredictRainfallRequest\x1a\x1f.inflow.v1.PredictRainfallReply\"&\x82\xd3\xe4\x93\x02 :\x01*\"\x1b/v1/inflow/predict-rainfall\x12\x8f\x01\n" +
	"\x15CalculateInflowVolume\x12'.inflow.v1.CalculateInflowVolumeRequest\x1a%.inflow.v1.CalculateInflowVolumeReply\"&\x82\xd3\xe4\x93\x02 :\x01*\"\x1b/v1/inflow/calculate-volumeB<\n" +
	"\rapi.inflow.v1P\x01Z)ReservoirFloodPrediction/api/inflow/v1;v1b\x06proto3"

var (
	file_api_inflow_v1_inflow_proto_rawDescOnce sync.Once
	file_api_inflow_v1_inflow_proto_rawDescData []byte
)

func file_api_inflow_v1_inflow_proto_rawDescGZIP() []byte {
	file_api_inflow_v1_inflow_proto_rawDescOnce.Do(func() {
		file_api_inflow_v1_inflow_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_inflow_v1_inflow_proto_rawDesc), len(file_api_inflow_v1_inflow_proto_rawDesc)))
	})
	return file_api_inflow_v1_inflow_proto_rawDescData
}

var file_api_inflow_v1_inflow_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_api_inflow_v1_inflow_proto_goTypes = []any{
	(*TimeSeriesDataPoint)(nil),          // 0: inflow.v1.TimeSeriesDataPoint
	(*HydrographDataPoint)(nil),          // 1: inflow.v1.HydrographDataPoint
	(*SimulateRainfallRequest)(nil),      // 2: inflow.v1.SimulateRainfallRequest
	(*SimulateRainfallReply)(nil),        // 3: inflow.v1.SimulateRainfallReply
	(*PredictRainfallRequest)(nil),       // 4: inflow.v1.PredictRainfallRequest
	(*PredictRainfallReply)(nil),         // 5: inflow.v1.PredictRainfallReply
	(*CalculateInflowVolumeRequest)(nil), // 6: inflow.v1.CalculateInflowVolumeRequest
	(*CalculateInflowVolumeReply)(nil),   // 7: inflow.v1.CalculateInflowVolumeReply
	(*timestamppb.Timestamp)(nil),        // 8: google.protobuf.Timestamp
}
var file_api_inflow_v1_inflow_proto_depIdxs = []int32{
	8,  // 0: inflow.v1.TimeSeriesDataPoint.time:type_name -> google.protobuf.Timestamp
	8,  // 1: inflow.v1.HydrographDataPoint.time:type_name -> google.protobuf.Timestamp
	0,  // 2: inflow.v1.SimulateRainfallReply.past_24h_rainfall:type_name -> inflow.v1.TimeSeriesDataPoint
	0,  // 3: inflow.v1.SimulateRainfallReply.past_15d_rainfall:type_name -> inflow.v1.TimeSeriesDataPoint
	0,  // 4: inflow.v1.PredictRainfallRequest.past_24h_rainfall:type_name -> inflow.v1.TimeSeriesDataPoint
	0,  // 5: inflow.v1.PredictRainfallReply.next_72h_rainfall:type_name -> inflow.v1.TimeSeriesDataPoint
	0,  // 6: inflow.v1.CalculateInflowVolumeRequest.rainfall_data:type_name -> inflow.v1.TimeSeriesDataPoint
	1,  // 7: inflow.v1.CalculateInflowVolumeReply.hydrograph_data:type_name -> inflow.v1.HydrographDataPoint
	8,  // 8: inflow.v1.CalculateInflowVolumeReply.peak_flow_time:type_name -> google.protobuf.Timestamp
	2,  // 9: inflow.v1.InflowService.SimulateRainfall:input_type -> inflow.v1.SimulateRainfallRequest
	4,  // 10: inflow.v1.InflowService.PredictRainfall:input_type -> inflow.v1.PredictRainfallRequest
	6,  // 11: inflow.v1.InflowService.CalculateInflowVolume:input_type -> inflow.v1.CalculateInflowVolumeRequest
	3,  // 12: inflow.v1.InflowService.SimulateRainfall:output_type -> inflow.v1.SimulateRainfallReply
	5,  // 13: inflow.v1.InflowService.PredictRainfall:output_type -> inflow.v1.PredictRainfallReply
	7,  // 14: inflow.v1.InflowService.CalculateInflowVolume:output_type -> inflow.v1.CalculateInflowVolumeReply
	12, // [12:15] is the sub-list for method output_type
	9,  // [9:12] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_api_inflow_v1_inflow_proto_init() }
func file_api_inflow_v1_inflow_proto_init() {
	if File_api_inflow_v1_inflow_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_inflow_v1_inflow_proto_rawDesc), len(file_api_inflow_v1_inflow_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_inflow_v1_inflow_proto_goTypes,
		DependencyIndexes: file_api_inflow_v1_inflow_proto_depIdxs,
		MessageInfos:      file_api_inflow_v1_inflow_proto_msgTypes,
	}.Build()
	File_api_inflow_v1_inflow_proto = out.File
	file_api_inflow_v1_inflow_proto_goTypes = nil
	file_api_inflow_v1_inflow_proto_depIdxs = nil
}
