// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.8.4
// - protoc             v6.30.2
// source: api/inflow/v1/inflow.proto

package v1

import (
	context "context"
	http "github.com/go-kratos/kratos/v2/transport/http"
	binding "github.com/go-kratos/kratos/v2/transport/http/binding"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = binding.EncodeURL

const _ = http.SupportPackageIsVersion1

const OperationInflowServiceCalculateInflowVolume = "/inflow.v1.InflowService/CalculateInflowVolume"
const OperationInflowServicePredictRainfall = "/inflow.v1.InflowService/PredictRainfall"
const OperationInflowServiceSimulateRainfall = "/inflow.v1.InflowService/SimulateRainfall"

type InflowServiceHTTPServer interface {
	// CalculateInflowVolume 计算入库洪水总量 (基于模拟和预测的降雨)
	CalculateInflowVolume(context.Context, *CalculateInflowVolumeRequest) (*CalculateInflowVolumeReply, error)
	// PredictRainfall 预测未来降雨数据 (基于模拟的历史数据)
	PredictRainfall(context.Context, *PredictRainfallRequest) (*PredictRainfallReply, error)
	// SimulateRainfall 模拟历史降雨数据
	SimulateRainfall(context.Context, *SimulateRainfallRequest) (*SimulateRainfallReply, error)
}

func RegisterInflowServiceHTTPServer(s *http.Server, srv InflowServiceHTTPServer) {
	r := s.Route("/")
	r.POST("/v1/inflow/simulate-rainfall", _InflowService_SimulateRainfall0_HTTP_Handler(srv))
	r.POST("/v1/inflow/predict-rainfall", _InflowService_PredictRainfall0_HTTP_Handler(srv))
	r.POST("/v1/inflow/calculate-volume", _InflowService_CalculateInflowVolume0_HTTP_Handler(srv))
}

func _InflowService_SimulateRainfall0_HTTP_Handler(srv InflowServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in SimulateRainfallRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationInflowServiceSimulateRainfall)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.SimulateRainfall(ctx, req.(*SimulateRainfallRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*SimulateRainfallReply)
		return ctx.Result(200, reply)
	}
}

func _InflowService_PredictRainfall0_HTTP_Handler(srv InflowServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in PredictRainfallRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationInflowServicePredictRainfall)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.PredictRainfall(ctx, req.(*PredictRainfallRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*PredictRainfallReply)
		return ctx.Result(200, reply)
	}
}

func _InflowService_CalculateInflowVolume0_HTTP_Handler(srv InflowServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in CalculateInflowVolumeRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationInflowServiceCalculateInflowVolume)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.CalculateInflowVolume(ctx, req.(*CalculateInflowVolumeRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*CalculateInflowVolumeReply)
		return ctx.Result(200, reply)
	}
}

type InflowServiceHTTPClient interface {
	CalculateInflowVolume(ctx context.Context, req *CalculateInflowVolumeRequest, opts ...http.CallOption) (rsp *CalculateInflowVolumeReply, err error)
	PredictRainfall(ctx context.Context, req *PredictRainfallRequest, opts ...http.CallOption) (rsp *PredictRainfallReply, err error)
	SimulateRainfall(ctx context.Context, req *SimulateRainfallRequest, opts ...http.CallOption) (rsp *SimulateRainfallReply, err error)
}

type InflowServiceHTTPClientImpl struct {
	cc *http.Client
}

func NewInflowServiceHTTPClient(client *http.Client) InflowServiceHTTPClient {
	return &InflowServiceHTTPClientImpl{client}
}

func (c *InflowServiceHTTPClientImpl) CalculateInflowVolume(ctx context.Context, in *CalculateInflowVolumeRequest, opts ...http.CallOption) (*CalculateInflowVolumeReply, error) {
	var out CalculateInflowVolumeReply
	pattern := "/v1/inflow/calculate-volume"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationInflowServiceCalculateInflowVolume))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *InflowServiceHTTPClientImpl) PredictRainfall(ctx context.Context, in *PredictRainfallRequest, opts ...http.CallOption) (*PredictRainfallReply, error) {
	var out PredictRainfallReply
	pattern := "/v1/inflow/predict-rainfall"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationInflowServicePredictRainfall))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *InflowServiceHTTPClientImpl) SimulateRainfall(ctx context.Context, in *SimulateRainfallRequest, opts ...http.CallOption) (*SimulateRainfallReply, error) {
	var out SimulateRainfallReply
	pattern := "/v1/inflow/simulate-rainfall"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationInflowServiceSimulateRainfall))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}
