// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.30.2
// source: api/inflow/v1/inflow.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	InflowService_SimulateRainfall_FullMethodName      = "/inflow.v1.InflowService/SimulateRainfall"
	InflowService_PredictRainfall_FullMethodName       = "/inflow.v1.InflowService/PredictRainfall"
	InflowService_CalculateInflowVolume_FullMethodName = "/inflow.v1.InflowService/CalculateInflowVolume"
)

// InflowServiceClient is the client API for InflowService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// InflowService 定义入库洪水分析相关的接口
type InflowServiceClient interface {
	// 模拟历史降雨数据
	SimulateRainfall(ctx context.Context, in *SimulateRainfallRequest, opts ...grpc.CallOption) (*SimulateRainfallReply, error)
	// 预测未来降雨数据 (基于模拟的历史数据)
	PredictRainfall(ctx context.Context, in *PredictRainfallRequest, opts ...grpc.CallOption) (*PredictRainfallReply, error)
	// 计算入库洪水总量 (基于模拟和预测的降雨)
	CalculateInflowVolume(ctx context.Context, in *CalculateInflowVolumeRequest, opts ...grpc.CallOption) (*CalculateInflowVolumeReply, error)
}

type inflowServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewInflowServiceClient(cc grpc.ClientConnInterface) InflowServiceClient {
	return &inflowServiceClient{cc}
}

func (c *inflowServiceClient) SimulateRainfall(ctx context.Context, in *SimulateRainfallRequest, opts ...grpc.CallOption) (*SimulateRainfallReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SimulateRainfallReply)
	err := c.cc.Invoke(ctx, InflowService_SimulateRainfall_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *inflowServiceClient) PredictRainfall(ctx context.Context, in *PredictRainfallRequest, opts ...grpc.CallOption) (*PredictRainfallReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PredictRainfallReply)
	err := c.cc.Invoke(ctx, InflowService_PredictRainfall_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *inflowServiceClient) CalculateInflowVolume(ctx context.Context, in *CalculateInflowVolumeRequest, opts ...grpc.CallOption) (*CalculateInflowVolumeReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CalculateInflowVolumeReply)
	err := c.cc.Invoke(ctx, InflowService_CalculateInflowVolume_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// InflowServiceServer is the server API for InflowService service.
// All implementations must embed UnimplementedInflowServiceServer
// for forward compatibility.
//
// InflowService 定义入库洪水分析相关的接口
type InflowServiceServer interface {
	// 模拟历史降雨数据
	SimulateRainfall(context.Context, *SimulateRainfallRequest) (*SimulateRainfallReply, error)
	// 预测未来降雨数据 (基于模拟的历史数据)
	PredictRainfall(context.Context, *PredictRainfallRequest) (*PredictRainfallReply, error)
	// 计算入库洪水总量 (基于模拟和预测的降雨)
	CalculateInflowVolume(context.Context, *CalculateInflowVolumeRequest) (*CalculateInflowVolumeReply, error)
	mustEmbedUnimplementedInflowServiceServer()
}

// UnimplementedInflowServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedInflowServiceServer struct{}

func (UnimplementedInflowServiceServer) SimulateRainfall(context.Context, *SimulateRainfallRequest) (*SimulateRainfallReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SimulateRainfall not implemented")
}
func (UnimplementedInflowServiceServer) PredictRainfall(context.Context, *PredictRainfallRequest) (*PredictRainfallReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PredictRainfall not implemented")
}
func (UnimplementedInflowServiceServer) CalculateInflowVolume(context.Context, *CalculateInflowVolumeRequest) (*CalculateInflowVolumeReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CalculateInflowVolume not implemented")
}
func (UnimplementedInflowServiceServer) mustEmbedUnimplementedInflowServiceServer() {}
func (UnimplementedInflowServiceServer) testEmbeddedByValue()                       {}

// UnsafeInflowServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to InflowServiceServer will
// result in compilation errors.
type UnsafeInflowServiceServer interface {
	mustEmbedUnimplementedInflowServiceServer()
}

func RegisterInflowServiceServer(s grpc.ServiceRegistrar, srv InflowServiceServer) {
	// If the following call pancis, it indicates UnimplementedInflowServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&InflowService_ServiceDesc, srv)
}

func _InflowService_SimulateRainfall_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SimulateRainfallRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InflowServiceServer).SimulateRainfall(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InflowService_SimulateRainfall_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InflowServiceServer).SimulateRainfall(ctx, req.(*SimulateRainfallRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _InflowService_PredictRainfall_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PredictRainfallRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InflowServiceServer).PredictRainfall(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InflowService_PredictRainfall_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InflowServiceServer).PredictRainfall(ctx, req.(*PredictRainfallRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _InflowService_CalculateInflowVolume_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CalculateInflowVolumeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InflowServiceServer).CalculateInflowVolume(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InflowService_CalculateInflowVolume_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InflowServiceServer).CalculateInflowVolume(ctx, req.(*CalculateInflowVolumeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// InflowService_ServiceDesc is the grpc.ServiceDesc for InflowService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var InflowService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "inflow.v1.InflowService",
	HandlerType: (*InflowServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SimulateRainfall",
			Handler:    _InflowService_SimulateRainfall_Handler,
		},
		{
			MethodName: "PredictRainfall",
			Handler:    _InflowService_PredictRainfall_Handler,
		},
		{
			MethodName: "CalculateInflowVolume",
			Handler:    _InflowService_CalculateInflowVolume_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/inflow/v1/inflow.proto",
}
