// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.8.4
// - protoc             v6.30.2
// source: api/routing/v1/routing.proto

package v1

import (
	context "context"
	http "github.com/go-kratos/kratos/v2/transport/http"
	binding "github.com/go-kratos/kratos/v2/transport/http/binding"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = binding.EncodeURL

const _ = http.SupportPackageIsVersion1

const OperationRoutingServiceRouteFlood = "/api.routing.v1.RoutingService/RouteFlood"

type RoutingServiceHTTPServer interface {
	// RouteFlood 执行水库调洪演算
	RouteFlood(context.Context, *FloodRoutingRequest) (*FloodRoutingReply, error)
}

func RegisterRoutingServiceHTTPServer(s *http.Server, srv RoutingServiceHTTPServer) {
	r := s.Route("/")
	r.POST("/v1/routing/route-flood", _RoutingService_RouteFlood0_HTTP_Handler(srv))
}

func _RoutingService_RouteFlood0_HTTP_Handler(srv RoutingServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in FloodRoutingRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationRoutingServiceRouteFlood)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.RouteFlood(ctx, req.(*FloodRoutingRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*FloodRoutingReply)
		return ctx.Result(200, reply)
	}
}

type RoutingServiceHTTPClient interface {
	RouteFlood(ctx context.Context, req *FloodRoutingRequest, opts ...http.CallOption) (rsp *FloodRoutingReply, err error)
}

type RoutingServiceHTTPClientImpl struct {
	cc *http.Client
}

func NewRoutingServiceHTTPClient(client *http.Client) RoutingServiceHTTPClient {
	return &RoutingServiceHTTPClientImpl{client}
}

func (c *RoutingServiceHTTPClientImpl) RouteFlood(ctx context.Context, in *FloodRoutingRequest, opts ...http.CallOption) (*FloodRoutingReply, error) {
	var out FloodRoutingReply
	pattern := "/v1/routing/route-flood"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationRoutingServiceRouteFlood))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}
