// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.2
// source: api/routing/v1/routing.proto

package v1

import (
	v1 "ReservoirFloodPrediction/api/inflow/v1"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 水库曲线上的一个点 (可用于库容曲线和泄流曲线)
type CurvePoint struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Level         float64                `protobuf:"fixed64,1,opt,name=level,proto3" json:"level,omitempty"` // 水位 (m)
	Value         float64                `protobuf:"fixed64,2,opt,name=value,proto3" json:"value,omitempty"` // 对应的值 (库容 10^4 m³ 或 流量 m³/s)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CurvePoint) Reset() {
	*x = CurvePoint{}
	mi := &file_api_routing_v1_routing_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CurvePoint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CurvePoint) ProtoMessage() {}

func (x *CurvePoint) ProtoReflect() protoreflect.Message {
	mi := &file_api_routing_v1_routing_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CurvePoint.ProtoReflect.Descriptor instead.
func (*CurvePoint) Descriptor() ([]byte, []int) {
	return file_api_routing_v1_routing_proto_rawDescGZIP(), []int{0}
}

func (x *CurvePoint) GetLevel() float64 {
	if x != nil {
		return x.Level
	}
	return 0
}

func (x *CurvePoint) GetValue() float64 {
	if x != nil {
		return x.Value
	}
	return 0
}

// 水库特征水位
type CharacteristicLevels struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	FloodLimitWaterLevel float64                `protobuf:"fixed64,1,opt,name=flood_limit_water_level,json=floodLimitWaterLevel,proto3" json:"flood_limit_water_level,omitempty"` // 汛限水位 (m)
	NormalWaterLevel     float64                `protobuf:"fixed64,2,opt,name=normal_water_level,json=normalWaterLevel,proto3" json:"normal_water_level,omitempty"`               // 正常蓄水位 (m)
	DesignFloodLevel     float64                `protobuf:"fixed64,3,opt,name=design_flood_level,json=designFloodLevel,proto3" json:"design_flood_level,omitempty"`               // 设计洪水位 (m)
	CheckFloodLevel      float64                `protobuf:"fixed64,4,opt,name=check_flood_level,json=checkFloodLevel,proto3" json:"check_flood_level,omitempty"`                  // 校核洪水位 (m)
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *CharacteristicLevels) Reset() {
	*x = CharacteristicLevels{}
	mi := &file_api_routing_v1_routing_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CharacteristicLevels) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CharacteristicLevels) ProtoMessage() {}

func (x *CharacteristicLevels) ProtoReflect() protoreflect.Message {
	mi := &file_api_routing_v1_routing_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CharacteristicLevels.ProtoReflect.Descriptor instead.
func (*CharacteristicLevels) Descriptor() ([]byte, []int) {
	return file_api_routing_v1_routing_proto_rawDescGZIP(), []int{1}
}

func (x *CharacteristicLevels) GetFloodLimitWaterLevel() float64 {
	if x != nil {
		return x.FloodLimitWaterLevel
	}
	return 0
}

func (x *CharacteristicLevels) GetNormalWaterLevel() float64 {
	if x != nil {
		return x.NormalWaterLevel
	}
	return 0
}

func (x *CharacteristicLevels) GetDesignFloodLevel() float64 {
	if x != nil {
		return x.DesignFloodLevel
	}
	return 0
}

func (x *CharacteristicLevels) GetCheckFloodLevel() float64 {
	if x != nil {
		return x.CheckFloodLevel
	}
	return 0
}

// 水库参数定义
type ReservoirParams struct {
	state                   protoimpl.MessageState `protogen:"open.v1"`
	Id                      string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`                                                                              // 水库唯一 ID
	Name                    string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`                                                                          // 水库名称
	StorageCurve            []*CurvePoint          `protobuf:"bytes,3,rep,name=storage_curve,json=storageCurve,proto3" json:"storage_curve,omitempty"`                                      // 库容曲线 (水位-库容) Z~W
	DischargeCurve          []*CurvePoint          `protobuf:"bytes,4,rep,name=discharge_curve,json=dischargeCurve,proto3" json:"discharge_curve,omitempty"`                                // 泄流能力曲线 (水位-下泄流量) Z~Q泄
	Levels                  *CharacteristicLevels  `protobuf:"bytes,5,opt,name=levels,proto3" json:"levels,omitempty"`                                                                      // 特征水位
	DownstreamSafeDischarge float64                `protobuf:"fixed64,6,opt,name=downstream_safe_discharge,json=downstreamSafeDischarge,proto3" json:"downstream_safe_discharge,omitempty"` // (可选) 下游安全泄量 (m³/s)
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *ReservoirParams) Reset() {
	*x = ReservoirParams{}
	mi := &file_api_routing_v1_routing_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReservoirParams) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReservoirParams) ProtoMessage() {}

func (x *ReservoirParams) ProtoReflect() protoreflect.Message {
	mi := &file_api_routing_v1_routing_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReservoirParams.ProtoReflect.Descriptor instead.
func (*ReservoirParams) Descriptor() ([]byte, []int) {
	return file_api_routing_v1_routing_proto_rawDescGZIP(), []int{2}
}

func (x *ReservoirParams) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ReservoirParams) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ReservoirParams) GetStorageCurve() []*CurvePoint {
	if x != nil {
		return x.StorageCurve
	}
	return nil
}

func (x *ReservoirParams) GetDischargeCurve() []*CurvePoint {
	if x != nil {
		return x.DischargeCurve
	}
	return nil
}

func (x *ReservoirParams) GetLevels() *CharacteristicLevels {
	if x != nil {
		return x.Levels
	}
	return nil
}

func (x *ReservoirParams) GetDownstreamSafeDischarge() float64 {
	if x != nil {
		return x.DownstreamSafeDischarge
	}
	return 0
}

// 调洪演算结果中的一个时间点数据
type RoutingResultPoint struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Time          *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=time,proto3" json:"time,omitempty"`                                          // 时间点
	WaterLevel    float64                `protobuf:"fixed64,2,opt,name=water_level,json=waterLevel,proto3" json:"water_level,omitempty"`          // 水库水位 (m)
	StorageVolume float64                `protobuf:"fixed64,3,opt,name=storage_volume,json=storageVolume,proto3" json:"storage_volume,omitempty"` // 水库库容 (10^4 m³)
	Outflow       float64                `protobuf:"fixed64,4,opt,name=outflow,proto3" json:"outflow,omitempty"`                                  // 出库流量 (m³/s)
	Inflow        float64                `protobuf:"fixed64,5,opt,name=inflow,proto3" json:"inflow,omitempty"`                                    // (可选) 对应的入库流量，方便绘图
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RoutingResultPoint) Reset() {
	*x = RoutingResultPoint{}
	mi := &file_api_routing_v1_routing_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoutingResultPoint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoutingResultPoint) ProtoMessage() {}

func (x *RoutingResultPoint) ProtoReflect() protoreflect.Message {
	mi := &file_api_routing_v1_routing_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoutingResultPoint.ProtoReflect.Descriptor instead.
func (*RoutingResultPoint) Descriptor() ([]byte, []int) {
	return file_api_routing_v1_routing_proto_rawDescGZIP(), []int{3}
}

func (x *RoutingResultPoint) GetTime() *timestamppb.Timestamp {
	if x != nil {
		return x.Time
	}
	return nil
}

func (x *RoutingResultPoint) GetWaterLevel() float64 {
	if x != nil {
		return x.WaterLevel
	}
	return 0
}

func (x *RoutingResultPoint) GetStorageVolume() float64 {
	if x != nil {
		return x.StorageVolume
	}
	return 0
}

func (x *RoutingResultPoint) GetOutflow() float64 {
	if x != nil {
		return x.Outflow
	}
	return 0
}

func (x *RoutingResultPoint) GetInflow() float64 {
	if x != nil {
		return x.Inflow
	}
	return 0
}

// 调洪演算请求
type FloodRoutingRequest struct {
	state             protoimpl.MessageState    `protogen:"open.v1"`
	ReservoirId       string                    `protobuf:"bytes,1,opt,name=reservoir_id,json=reservoirId,proto3" json:"reservoir_id,omitempty"`                       // 要计算的水库 ID
	InflowHydrograph  []*v1.HydrographDataPoint `protobuf:"bytes,2,rep,name=inflow_hydrograph,json=inflowHydrograph,proto3" json:"inflow_hydrograph,omitempty"`        // 输入的入库流量过程线
	InitialWaterLevel float64                   `protobuf:"fixed64,3,opt,name=initial_water_level,json=initialWaterLevel,proto3" json:"initial_water_level,omitempty"` // 初始水库水位 (m)
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *FloodRoutingRequest) Reset() {
	*x = FloodRoutingRequest{}
	mi := &file_api_routing_v1_routing_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FloodRoutingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FloodRoutingRequest) ProtoMessage() {}

func (x *FloodRoutingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_routing_v1_routing_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FloodRoutingRequest.ProtoReflect.Descriptor instead.
func (*FloodRoutingRequest) Descriptor() ([]byte, []int) {
	return file_api_routing_v1_routing_proto_rawDescGZIP(), []int{4}
}

func (x *FloodRoutingRequest) GetReservoirId() string {
	if x != nil {
		return x.ReservoirId
	}
	return ""
}

func (x *FloodRoutingRequest) GetInflowHydrograph() []*v1.HydrographDataPoint {
	if x != nil {
		return x.InflowHydrograph
	}
	return nil
}

func (x *FloodRoutingRequest) GetInitialWaterLevel() float64 {
	if x != nil {
		return x.InitialWaterLevel
	}
	return 0
}

// 调洪演算响应
type FloodRoutingReply struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Results            []*RoutingResultPoint  `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`                                                     // 调洪结果过程线
	PeakWaterLevel     float64                `protobuf:"fixed64,2,opt,name=peak_water_level,json=peakWaterLevel,proto3" json:"peak_water_level,omitempty"`             // 最高水位 (m)
	PeakWaterLevelTime *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=peak_water_level_time,json=peakWaterLevelTime,proto3" json:"peak_water_level_time,omitempty"` // 最高水位出现时间
	PeakOutflow        float64                `protobuf:"fixed64,4,opt,name=peak_outflow,json=peakOutflow,proto3" json:"peak_outflow,omitempty"`                        // 最大出库流量 (m³/s)
	PeakOutflowTime    *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=peak_outflow_time,json=peakOutflowTime,proto3" json:"peak_outflow_time,omitempty"`            // 最大出库流量出现时间
	MaxStorageVolume   float64                `protobuf:"fixed64,6,opt,name=max_storage_volume,json=maxStorageVolume,proto3" json:"max_storage_volume,omitempty"`       // 最大库容 (10^4 m³)
	Message            string                 `protobuf:"bytes,7,opt,name=message,proto3" json:"message,omitempty"`                                                     // 状态或错误信息
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *FloodRoutingReply) Reset() {
	*x = FloodRoutingReply{}
	mi := &file_api_routing_v1_routing_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FloodRoutingReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FloodRoutingReply) ProtoMessage() {}

func (x *FloodRoutingReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_routing_v1_routing_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FloodRoutingReply.ProtoReflect.Descriptor instead.
func (*FloodRoutingReply) Descriptor() ([]byte, []int) {
	return file_api_routing_v1_routing_proto_rawDescGZIP(), []int{5}
}

func (x *FloodRoutingReply) GetResults() []*RoutingResultPoint {
	if x != nil {
		return x.Results
	}
	return nil
}

func (x *FloodRoutingReply) GetPeakWaterLevel() float64 {
	if x != nil {
		return x.PeakWaterLevel
	}
	return 0
}

func (x *FloodRoutingReply) GetPeakWaterLevelTime() *timestamppb.Timestamp {
	if x != nil {
		return x.PeakWaterLevelTime
	}
	return nil
}

func (x *FloodRoutingReply) GetPeakOutflow() float64 {
	if x != nil {
		return x.PeakOutflow
	}
	return 0
}

func (x *FloodRoutingReply) GetPeakOutflowTime() *timestamppb.Timestamp {
	if x != nil {
		return x.PeakOutflowTime
	}
	return nil
}

func (x *FloodRoutingReply) GetMaxStorageVolume() float64 {
	if x != nil {
		return x.MaxStorageVolume
	}
	return 0
}

func (x *FloodRoutingReply) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_api_routing_v1_routing_proto protoreflect.FileDescriptor

const file_api_routing_v1_routing_proto_rawDesc = "" +
	"\n" +
	"\x1capi/routing/v1/routing.proto\x12\x0eapi.routing.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1aapi/inflow/v1/inflow.proto\x1a\x1cgoogle/api/annotations.proto\"8\n" +
	"\n" +
	"CurvePoint\x12\x14\n" +
	"\x05level\x18\x01 \x01(\x01R\x05level\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x01R\x05value\"\xd5\x01\n" +
	"\x14CharacteristicLevels\x125\n" +
	"\x17flood_limit_water_level\x18\x01 \x01(\x01R\x14floodLimitWaterLevel\x12,\n" +
	"\x12normal_water_level\x18\x02 \x01(\x01R\x10normalWaterLevel\x12,\n" +
	"\x12design_flood_level\x18\x03 \x01(\x01R\x10designFloodLevel\x12*\n" +
	"\x11check_flood_level\x18\x04 \x01(\x01R\x0fcheckFloodLevel\"\xb5\x02\n" +
	"\x0fReservoirParams\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12?\n" +
	"\rstorage_curve\x18\x03 \x03(\v2\x1a.api.routing.v1.CurvePointR\fstorageCurve\x12C\n" +
	"\x0fdischarge_curve\x18\x04 \x03(\v2\x1a.api.routing.v1.CurvePointR\x0edischargeCurve\x12<\n" +
	"\x06levels\x18\x05 \x01(\v2$.api.routing.v1.CharacteristicLevelsR\x06levels\x12:\n" +
	"\x19downstream_safe_discharge\x18\x06 \x01(\x01R\x17downstreamSafeDischarge\"\xbe\x01\n" +
	"\x12RoutingResultPoint\x12.\n" +
	"\x04time\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\x04time\x12\x1f\n" +
	"\vwater_level\x18\x02 \x01(\x01R\n" +
	"waterLevel\x12%\n" +
	"\x0estorage_volume\x18\x03 \x01(\x01R\rstorageVolume\x12\x18\n" +
	"\aoutflow\x18\x04 \x01(\x01R\aoutflow\x12\x16\n" +
	"\x06inflow\x18\x05 \x01(\x01R\x06inflow\"\xb5\x01\n" +
	"\x13FloodRoutingRequest\x12!\n" +
	"\freservoir_id\x18\x01 \x01(\tR\vreservoirId\x12K\n" +
	"\x11inflow_hydrograph\x18\x02 \x03(\v2\x1e.inflow.v1.HydrographDataPointR\x10inflowHydrograph\x12.\n" +
	"\x13initial_water_level\x18\x03 \x01(\x01R\x11initialWaterLevel\"\xfd\x02\n" +
	"\x11FloodRoutingReply\x12<\n" +
	"\aresults\x18\x01 \x03(\v2\".api.routing.v1.RoutingResultPointR\aresults\x12(\n" +
	"\x10peak_water_level\x18\x02 \x01(\x01R\x0epeakWaterLevel\x12M\n" +
	"\x15peak_water_level_time\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\x12peakWaterLevelTime\x12!\n" +
	"\fpeak_outflow\x18\x04 \x01(\x01R\vpeakOutflow\x12F\n" +
	"\x11peak_outflow_time\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\x0fpeakOutflowTime\x12,\n" +
	"\x12max_storage_volume\x18\x06 \x01(\x01R\x10maxStorageVolume\x12\x18\n" +
	"\amessage\x18\a \x01(\tR\amessage2\x8a\x01\n" +
	"\x0eRoutingService\x12x\n" +
	"\n" +
	"RouteFlood\x12#.api.routing.v1.FloodRoutingRequest\x1a!.api.routing.v1.FloodRoutingReply\"\"\x82\xd3\xe4\x93\x02\x1c:\x01*\"\x17/v1/routing/route-floodB,Z*ReservoirFloodPrediction/api/routing/v1;v1b\x06proto3"

var (
	file_api_routing_v1_routing_proto_rawDescOnce sync.Once
	file_api_routing_v1_routing_proto_rawDescData []byte
)

func file_api_routing_v1_routing_proto_rawDescGZIP() []byte {
	file_api_routing_v1_routing_proto_rawDescOnce.Do(func() {
		file_api_routing_v1_routing_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_routing_v1_routing_proto_rawDesc), len(file_api_routing_v1_routing_proto_rawDesc)))
	})
	return file_api_routing_v1_routing_proto_rawDescData
}

var file_api_routing_v1_routing_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_api_routing_v1_routing_proto_goTypes = []any{
	(*CurvePoint)(nil),             // 0: api.routing.v1.CurvePoint
	(*CharacteristicLevels)(nil),   // 1: api.routing.v1.CharacteristicLevels
	(*ReservoirParams)(nil),        // 2: api.routing.v1.ReservoirParams
	(*RoutingResultPoint)(nil),     // 3: api.routing.v1.RoutingResultPoint
	(*FloodRoutingRequest)(nil),    // 4: api.routing.v1.FloodRoutingRequest
	(*FloodRoutingReply)(nil),      // 5: api.routing.v1.FloodRoutingReply
	(*timestamppb.Timestamp)(nil),  // 6: google.protobuf.Timestamp
	(*v1.HydrographDataPoint)(nil), // 7: inflow.v1.HydrographDataPoint
}
var file_api_routing_v1_routing_proto_depIdxs = []int32{
	0, // 0: api.routing.v1.ReservoirParams.storage_curve:type_name -> api.routing.v1.CurvePoint
	0, // 1: api.routing.v1.ReservoirParams.discharge_curve:type_name -> api.routing.v1.CurvePoint
	1, // 2: api.routing.v1.ReservoirParams.levels:type_name -> api.routing.v1.CharacteristicLevels
	6, // 3: api.routing.v1.RoutingResultPoint.time:type_name -> google.protobuf.Timestamp
	7, // 4: api.routing.v1.FloodRoutingRequest.inflow_hydrograph:type_name -> inflow.v1.HydrographDataPoint
	3, // 5: api.routing.v1.FloodRoutingReply.results:type_name -> api.routing.v1.RoutingResultPoint
	6, // 6: api.routing.v1.FloodRoutingReply.peak_water_level_time:type_name -> google.protobuf.Timestamp
	6, // 7: api.routing.v1.FloodRoutingReply.peak_outflow_time:type_name -> google.protobuf.Timestamp
	4, // 8: api.routing.v1.RoutingService.RouteFlood:input_type -> api.routing.v1.FloodRoutingRequest
	5, // 9: api.routing.v1.RoutingService.RouteFlood:output_type -> api.routing.v1.FloodRoutingReply
	9, // [9:10] is the sub-list for method output_type
	8, // [8:9] is the sub-list for method input_type
	8, // [8:8] is the sub-list for extension type_name
	8, // [8:8] is the sub-list for extension extendee
	0, // [0:8] is the sub-list for field type_name
}

func init() { file_api_routing_v1_routing_proto_init() }
func file_api_routing_v1_routing_proto_init() {
	if File_api_routing_v1_routing_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_routing_v1_routing_proto_rawDesc), len(file_api_routing_v1_routing_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_routing_v1_routing_proto_goTypes,
		DependencyIndexes: file_api_routing_v1_routing_proto_depIdxs,
		MessageInfos:      file_api_routing_v1_routing_proto_msgTypes,
	}.Build()
	File_api_routing_v1_routing_proto = out.File
	file_api_routing_v1_routing_proto_goTypes = nil
	file_api_routing_v1_routing_proto_depIdxs = nil
}
