// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"ReservoirFloodPrediction/internal/biz"
	"ReservoirFloodPrediction/internal/conf"
	"ReservoirFloodPrediction/internal/data"
	"ReservoirFloodPrediction/internal/server"
	"ReservoirFloodPrediction/internal/service"
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
)

import (
	_ "go.uber.org/automaxprocs"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(bootstrap *conf.Bootstrap, logger log.Logger) (*kratos.App, func(), error) {
	confServer := provideServerConfig(bootstrap)
	confData := provideDataConfig(bootstrap)
	dataData, cleanup, err := data.NewData(confData, logger)
	if err != nil {
		return nil, nil, err
	}
	userRepo := data.NewUserRepo(dataData, logger)
	userUsecase := biz.NewUserUsecase(userRepo, logger)
	userService := service.NewUserService(userUsecase, logger)
	mapDataRepo := data.NewMapDataRepo(dataData, logger)
	mapDataUseCase := biz.NewMapDataUseCase(mapDataRepo)
	mapDataService := service.NewMapDataService(mapDataUseCase, logger)
	confBiz := provideBizConfig(bootstrap)
	inflowUsecase := biz.NewInflowUsecase(mapDataRepo, confBiz, logger)
	inflowService := service.NewInflowService(inflowUsecase, logger)
	routingRepo := data.NewRoutingRepo(dataData)
	routingUseCase := biz.NewRoutingUseCase(routingRepo)
	routingService := service.NewRoutingService(routingUseCase)
	httpServer := server.NewHTTPServer(confServer, userService, mapDataService, inflowService, routingService, logger)
	app := newApp(logger, httpServer)
	return app, func() {
		cleanup()
	}, nil
}

// wire.go:

// Provider function to extract Server config from Bootstrap
func provideServerConfig(bc *conf.Bootstrap) *conf.Server {
	return bc.Server
}

// Provider function to extract Data config from Bootstrap
func provideDataConfig(bc *conf.Bootstrap) *conf.Data {
	return bc.Data
}

// Provider function to extract Biz config from Bootstrap
func provideBizConfig(bc *conf.Bootstrap) *conf.Biz {
	if bc == nil {
		return nil
	}
	return bc.Biz
}
