// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.30.2
// source: api/mapdata/v1/mapdata.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	MapData_ListBasins_FullMethodName     = "/mapdata.v1.MapData/ListBasins"
	MapData_ListReservoirs_FullMethodName = "/mapdata.v1.MapData/ListReservoirs"
	MapData_GenerateCurves_FullMethodName = "/mapdata.v1.MapData/GenerateCurves"
	MapData_GetCurves_FullMethodName      = "/mapdata.v1.MapData/GetCurves"
	MapData_UpdateCurves_FullMethodName   = "/mapdata.v1.MapData/UpdateCurves"
)

// MapDataClient is the client API for MapData service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// MapData 服务，提供地图所需的数据
type MapDataClient interface {
	// 获取流域列表
	ListBasins(ctx context.Context, in *ListBasinsRequest, opts ...grpc.CallOption) (*ListBasinsReply, error)
	// 获取水库/雨量站列表
	ListReservoirs(ctx context.Context, in *ListReservoirsRequest, opts ...grpc.CallOption) (*ListReservoirsReply, error)
	// 生成指定水库的模拟曲线数据
	GenerateCurves(ctx context.Context, in *GenerateCurvesRequest, opts ...grpc.CallOption) (*GenerateCurvesReply, error)
	// 获取指定水库的库容和泄流曲线数据
	GetCurves(ctx context.Context, in *GetCurvesRequest, opts ...grpc.CallOption) (*GetCurvesReply, error)
	// 更新指定水库的库容和泄流曲线数据
	UpdateCurves(ctx context.Context, in *UpdateCurvesRequest, opts ...grpc.CallOption) (*UpdateCurvesReply, error)
}

type mapDataClient struct {
	cc grpc.ClientConnInterface
}

func NewMapDataClient(cc grpc.ClientConnInterface) MapDataClient {
	return &mapDataClient{cc}
}

func (c *mapDataClient) ListBasins(ctx context.Context, in *ListBasinsRequest, opts ...grpc.CallOption) (*ListBasinsReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListBasinsReply)
	err := c.cc.Invoke(ctx, MapData_ListBasins_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mapDataClient) ListReservoirs(ctx context.Context, in *ListReservoirsRequest, opts ...grpc.CallOption) (*ListReservoirsReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListReservoirsReply)
	err := c.cc.Invoke(ctx, MapData_ListReservoirs_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mapDataClient) GenerateCurves(ctx context.Context, in *GenerateCurvesRequest, opts ...grpc.CallOption) (*GenerateCurvesReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GenerateCurvesReply)
	err := c.cc.Invoke(ctx, MapData_GenerateCurves_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mapDataClient) GetCurves(ctx context.Context, in *GetCurvesRequest, opts ...grpc.CallOption) (*GetCurvesReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetCurvesReply)
	err := c.cc.Invoke(ctx, MapData_GetCurves_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mapDataClient) UpdateCurves(ctx context.Context, in *UpdateCurvesRequest, opts ...grpc.CallOption) (*UpdateCurvesReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateCurvesReply)
	err := c.cc.Invoke(ctx, MapData_UpdateCurves_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MapDataServer is the server API for MapData service.
// All implementations must embed UnimplementedMapDataServer
// for forward compatibility.
//
// MapData 服务，提供地图所需的数据
type MapDataServer interface {
	// 获取流域列表
	ListBasins(context.Context, *ListBasinsRequest) (*ListBasinsReply, error)
	// 获取水库/雨量站列表
	ListReservoirs(context.Context, *ListReservoirsRequest) (*ListReservoirsReply, error)
	// 生成指定水库的模拟曲线数据
	GenerateCurves(context.Context, *GenerateCurvesRequest) (*GenerateCurvesReply, error)
	// 获取指定水库的库容和泄流曲线数据
	GetCurves(context.Context, *GetCurvesRequest) (*GetCurvesReply, error)
	// 更新指定水库的库容和泄流曲线数据
	UpdateCurves(context.Context, *UpdateCurvesRequest) (*UpdateCurvesReply, error)
	mustEmbedUnimplementedMapDataServer()
}

// UnimplementedMapDataServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMapDataServer struct{}

func (UnimplementedMapDataServer) ListBasins(context.Context, *ListBasinsRequest) (*ListBasinsReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListBasins not implemented")
}
func (UnimplementedMapDataServer) ListReservoirs(context.Context, *ListReservoirsRequest) (*ListReservoirsReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListReservoirs not implemented")
}
func (UnimplementedMapDataServer) GenerateCurves(context.Context, *GenerateCurvesRequest) (*GenerateCurvesReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GenerateCurves not implemented")
}
func (UnimplementedMapDataServer) GetCurves(context.Context, *GetCurvesRequest) (*GetCurvesReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCurves not implemented")
}
func (UnimplementedMapDataServer) UpdateCurves(context.Context, *UpdateCurvesRequest) (*UpdateCurvesReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateCurves not implemented")
}
func (UnimplementedMapDataServer) mustEmbedUnimplementedMapDataServer() {}
func (UnimplementedMapDataServer) testEmbeddedByValue()                 {}

// UnsafeMapDataServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MapDataServer will
// result in compilation errors.
type UnsafeMapDataServer interface {
	mustEmbedUnimplementedMapDataServer()
}

func RegisterMapDataServer(s grpc.ServiceRegistrar, srv MapDataServer) {
	// If the following call pancis, it indicates UnimplementedMapDataServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&MapData_ServiceDesc, srv)
}

func _MapData_ListBasins_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListBasinsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MapDataServer).ListBasins(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MapData_ListBasins_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MapDataServer).ListBasins(ctx, req.(*ListBasinsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MapData_ListReservoirs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListReservoirsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MapDataServer).ListReservoirs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MapData_ListReservoirs_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MapDataServer).ListReservoirs(ctx, req.(*ListReservoirsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MapData_GenerateCurves_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GenerateCurvesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MapDataServer).GenerateCurves(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MapData_GenerateCurves_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MapDataServer).GenerateCurves(ctx, req.(*GenerateCurvesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MapData_GetCurves_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCurvesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MapDataServer).GetCurves(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MapData_GetCurves_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MapDataServer).GetCurves(ctx, req.(*GetCurvesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MapData_UpdateCurves_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateCurvesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MapDataServer).UpdateCurves(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MapData_UpdateCurves_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MapDataServer).UpdateCurves(ctx, req.(*UpdateCurvesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// MapData_ServiceDesc is the grpc.ServiceDesc for MapData service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MapData_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "mapdata.v1.MapData",
	HandlerType: (*MapDataServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListBasins",
			Handler:    _MapData_ListBasins_Handler,
		},
		{
			MethodName: "ListReservoirs",
			Handler:    _MapData_ListReservoirs_Handler,
		},
		{
			MethodName: "GenerateCurves",
			Handler:    _MapData_GenerateCurves_Handler,
		},
		{
			MethodName: "GetCurves",
			Handler:    _MapData_GetCurves_Handler,
		},
		{
			MethodName: "UpdateCurves",
			Handler:    _MapData_UpdateCurves_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/mapdata/v1/mapdata.proto",
}
