// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.8.4
// - protoc             v6.30.2
// source: api/mapdata/v1/mapdata.proto

package v1

import (
	context "context"
	http "github.com/go-kratos/kratos/v2/transport/http"
	binding "github.com/go-kratos/kratos/v2/transport/http/binding"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = binding.EncodeURL

const _ = http.SupportPackageIsVersion1

const OperationMapDataGenerateCurves = "/mapdata.v1.MapData/GenerateCurves"
const OperationMapDataGetCurves = "/mapdata.v1.MapData/GetCurves"
const OperationMapDataListBasins = "/mapdata.v1.MapData/ListBasins"
const OperationMapDataListReservoirs = "/mapdata.v1.MapData/ListReservoirs"
const OperationMapDataUpdateCurves = "/mapdata.v1.MapData/UpdateCurves"

type MapDataHTTPServer interface {
	// GenerateCurves 生成指定水库的模拟曲线数据
	GenerateCurves(context.Context, *GenerateCurvesRequest) (*GenerateCurvesReply, error)
	// GetCurves 获取指定水库的库容和泄流曲线数据
	GetCurves(context.Context, *GetCurvesRequest) (*GetCurvesReply, error)
	// ListBasins 获取流域列表
	ListBasins(context.Context, *ListBasinsRequest) (*ListBasinsReply, error)
	// ListReservoirs 获取水库/雨量站列表
	ListReservoirs(context.Context, *ListReservoirsRequest) (*ListReservoirsReply, error)
	// UpdateCurves 更新指定水库的库容和泄流曲线数据
	UpdateCurves(context.Context, *UpdateCurvesRequest) (*UpdateCurvesReply, error)
}

func RegisterMapDataHTTPServer(s *http.Server, srv MapDataHTTPServer) {
	r := s.Route("/")
	r.GET("/v1/map/basins", _MapData_ListBasins0_HTTP_Handler(srv))
	r.GET("/v1/map/reservoirs", _MapData_ListReservoirs0_HTTP_Handler(srv))
	r.POST("/v1/reservoirs/{reservoir_id}/generate-curves", _MapData_GenerateCurves0_HTTP_Handler(srv))
	r.GET("/v1/reservoirs/{reservoir_id}/curves", _MapData_GetCurves0_HTTP_Handler(srv))
	r.PUT("/v1/reservoirs/{reservoir_id}/curves", _MapData_UpdateCurves0_HTTP_Handler(srv))
}

func _MapData_ListBasins0_HTTP_Handler(srv MapDataHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ListBasinsRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationMapDataListBasins)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListBasins(ctx, req.(*ListBasinsRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ListBasinsReply)
		return ctx.Result(200, reply)
	}
}

func _MapData_ListReservoirs0_HTTP_Handler(srv MapDataHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ListReservoirsRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationMapDataListReservoirs)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListReservoirs(ctx, req.(*ListReservoirsRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ListReservoirsReply)
		return ctx.Result(200, reply)
	}
}

func _MapData_GenerateCurves0_HTTP_Handler(srv MapDataHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GenerateCurvesRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationMapDataGenerateCurves)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GenerateCurves(ctx, req.(*GenerateCurvesRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*GenerateCurvesReply)
		return ctx.Result(200, reply)
	}
}

func _MapData_GetCurves0_HTTP_Handler(srv MapDataHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetCurvesRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationMapDataGetCurves)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetCurves(ctx, req.(*GetCurvesRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*GetCurvesReply)
		return ctx.Result(200, reply)
	}
}

func _MapData_UpdateCurves0_HTTP_Handler(srv MapDataHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in UpdateCurvesRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationMapDataUpdateCurves)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.UpdateCurves(ctx, req.(*UpdateCurvesRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*UpdateCurvesReply)
		return ctx.Result(200, reply)
	}
}

type MapDataHTTPClient interface {
	GenerateCurves(ctx context.Context, req *GenerateCurvesRequest, opts ...http.CallOption) (rsp *GenerateCurvesReply, err error)
	GetCurves(ctx context.Context, req *GetCurvesRequest, opts ...http.CallOption) (rsp *GetCurvesReply, err error)
	ListBasins(ctx context.Context, req *ListBasinsRequest, opts ...http.CallOption) (rsp *ListBasinsReply, err error)
	ListReservoirs(ctx context.Context, req *ListReservoirsRequest, opts ...http.CallOption) (rsp *ListReservoirsReply, err error)
	UpdateCurves(ctx context.Context, req *UpdateCurvesRequest, opts ...http.CallOption) (rsp *UpdateCurvesReply, err error)
}

type MapDataHTTPClientImpl struct {
	cc *http.Client
}

func NewMapDataHTTPClient(client *http.Client) MapDataHTTPClient {
	return &MapDataHTTPClientImpl{client}
}

func (c *MapDataHTTPClientImpl) GenerateCurves(ctx context.Context, in *GenerateCurvesRequest, opts ...http.CallOption) (*GenerateCurvesReply, error) {
	var out GenerateCurvesReply
	pattern := "/v1/reservoirs/{reservoir_id}/generate-curves"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationMapDataGenerateCurves))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *MapDataHTTPClientImpl) GetCurves(ctx context.Context, in *GetCurvesRequest, opts ...http.CallOption) (*GetCurvesReply, error) {
	var out GetCurvesReply
	pattern := "/v1/reservoirs/{reservoir_id}/curves"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationMapDataGetCurves))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *MapDataHTTPClientImpl) ListBasins(ctx context.Context, in *ListBasinsRequest, opts ...http.CallOption) (*ListBasinsReply, error) {
	var out ListBasinsReply
	pattern := "/v1/map/basins"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationMapDataListBasins))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *MapDataHTTPClientImpl) ListReservoirs(ctx context.Context, in *ListReservoirsRequest, opts ...http.CallOption) (*ListReservoirsReply, error) {
	var out ListReservoirsReply
	pattern := "/v1/map/reservoirs"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationMapDataListReservoirs))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *MapDataHTTPClientImpl) UpdateCurves(ctx context.Context, in *UpdateCurvesRequest, opts ...http.CallOption) (*UpdateCurvesReply, error) {
	var out UpdateCurvesReply
	pattern := "/v1/reservoirs/{reservoir_id}/curves"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationMapDataUpdateCurves))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "PUT", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}
