// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.2
// source: api/mapdata/v1/mapdata.proto

package v1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	wrapperspb "google.golang.org/protobuf/types/known/wrapperspb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// CurvePoint 定义水位和对应值的点
type CurvePoint struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Level float64                `protobuf:"fixed64,1,opt,name=level,proto3" json:"level,omitempty"` // 水位 (m)
	Value float64                `protobuf:"fixed64,2,opt,name=value,proto3" json:"value,omitempty"` // 对应的值 (库容 - 万m³, 或 流量 - m³/s)
	// 在更新时，可以通过 ID 识别现有记录，或 ID 为空表示新增
	Id            *wrapperspb.UInt64Value `protobuf:"bytes,3,opt,name=id,proto3" json:"id,omitempty"` // 可选的数据库记录 ID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CurvePoint) Reset() {
	*x = CurvePoint{}
	mi := &file_api_mapdata_v1_mapdata_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CurvePoint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CurvePoint) ProtoMessage() {}

func (x *CurvePoint) ProtoReflect() protoreflect.Message {
	mi := &file_api_mapdata_v1_mapdata_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CurvePoint.ProtoReflect.Descriptor instead.
func (*CurvePoint) Descriptor() ([]byte, []int) {
	return file_api_mapdata_v1_mapdata_proto_rawDescGZIP(), []int{0}
}

func (x *CurvePoint) GetLevel() float64 {
	if x != nil {
		return x.Level
	}
	return 0
}

func (x *CurvePoint) GetValue() float64 {
	if x != nil {
		return x.Value
	}
	return 0
}

func (x *CurvePoint) GetId() *wrapperspb.UInt64Value {
	if x != nil {
		return x.Id
	}
	return nil
}

// BasinInfo 消息结构，对应业务层的 BasinInfo
type BasinInfo struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"` // 添加 ID 字段
	BasinName       string                 `protobuf:"bytes,2,opt,name=basin_name,json=basinName,proto3" json:"basin_name,omitempty"`
	ControlArea     float64                `protobuf:"fixed64,3,opt,name=control_area,json=controlArea,proto3" json:"control_area,omitempty"`
	MainStreamSlope float64                `protobuf:"fixed64,4,opt,name=main_stream_slope,json=mainStreamSlope,proto3" json:"main_stream_slope,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *BasinInfo) Reset() {
	*x = BasinInfo{}
	mi := &file_api_mapdata_v1_mapdata_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BasinInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BasinInfo) ProtoMessage() {}

func (x *BasinInfo) ProtoReflect() protoreflect.Message {
	mi := &file_api_mapdata_v1_mapdata_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BasinInfo.ProtoReflect.Descriptor instead.
func (*BasinInfo) Descriptor() ([]byte, []int) {
	return file_api_mapdata_v1_mapdata_proto_rawDescGZIP(), []int{1}
}

func (x *BasinInfo) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *BasinInfo) GetBasinName() string {
	if x != nil {
		return x.BasinName
	}
	return ""
}

func (x *BasinInfo) GetControlArea() float64 {
	if x != nil {
		return x.ControlArea
	}
	return 0
}

func (x *BasinInfo) GetMainStreamSlope() float64 {
	if x != nil {
		return x.MainStreamSlope
	}
	return 0
}

// ReservoirInfo 消息结构，对应 Service 层 ListReservoirs 返回的列表项
// (原 Reservoir 消息重命名)
type ReservoirInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Latitude      float64                `protobuf:"fixed64,3,opt,name=latitude,proto3" json:"latitude,omitempty"`
	Longitude     float64                `protobuf:"fixed64,4,opt,name=longitude,proto3" json:"longitude,omitempty"`
	ControlArea   float64                `protobuf:"fixed64,5,opt,name=control_area,json=controlArea,proto3" json:"control_area,omitempty"` // 作为雨量站的控制面积
	Weight        float64                `protobuf:"fixed64,6,opt,name=weight,proto3" json:"weight,omitempty"`                              // 作为雨量站的权重
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReservoirInfo) Reset() {
	*x = ReservoirInfo{}
	mi := &file_api_mapdata_v1_mapdata_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReservoirInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReservoirInfo) ProtoMessage() {}

func (x *ReservoirInfo) ProtoReflect() protoreflect.Message {
	mi := &file_api_mapdata_v1_mapdata_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReservoirInfo.ProtoReflect.Descriptor instead.
func (*ReservoirInfo) Descriptor() ([]byte, []int) {
	return file_api_mapdata_v1_mapdata_proto_rawDescGZIP(), []int{2}
}

func (x *ReservoirInfo) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ReservoirInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ReservoirInfo) GetLatitude() float64 {
	if x != nil {
		return x.Latitude
	}
	return 0
}

func (x *ReservoirInfo) GetLongitude() float64 {
	if x != nil {
		return x.Longitude
	}
	return 0
}

func (x *ReservoirInfo) GetControlArea() float64 {
	if x != nil {
		return x.ControlArea
	}
	return 0
}

func (x *ReservoirInfo) GetWeight() float64 {
	if x != nil {
		return x.Weight
	}
	return 0
}

// --- ListBasins 相关消息 ---
type ListBasinsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListBasinsRequest) Reset() {
	*x = ListBasinsRequest{}
	mi := &file_api_mapdata_v1_mapdata_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListBasinsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListBasinsRequest) ProtoMessage() {}

func (x *ListBasinsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_mapdata_v1_mapdata_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListBasinsRequest.ProtoReflect.Descriptor instead.
func (*ListBasinsRequest) Descriptor() ([]byte, []int) {
	return file_api_mapdata_v1_mapdata_proto_rawDescGZIP(), []int{3}
}

type ListBasinsReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Basins        []*BasinInfo           `protobuf:"bytes,1,rep,name=basins,proto3" json:"basins,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListBasinsReply) Reset() {
	*x = ListBasinsReply{}
	mi := &file_api_mapdata_v1_mapdata_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListBasinsReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListBasinsReply) ProtoMessage() {}

func (x *ListBasinsReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_mapdata_v1_mapdata_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListBasinsReply.ProtoReflect.Descriptor instead.
func (*ListBasinsReply) Descriptor() ([]byte, []int) {
	return file_api_mapdata_v1_mapdata_proto_rawDescGZIP(), []int{4}
}

func (x *ListBasinsReply) GetBasins() []*BasinInfo {
	if x != nil {
		return x.Basins
	}
	return nil
}

// --- ListReservoirs 相关消息 ---
type ListReservoirsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListReservoirsRequest) Reset() {
	*x = ListReservoirsRequest{}
	mi := &file_api_mapdata_v1_mapdata_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListReservoirsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListReservoirsRequest) ProtoMessage() {}

func (x *ListReservoirsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_mapdata_v1_mapdata_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListReservoirsRequest.ProtoReflect.Descriptor instead.
func (*ListReservoirsRequest) Descriptor() ([]byte, []int) {
	return file_api_mapdata_v1_mapdata_proto_rawDescGZIP(), []int{5}
}

type ListReservoirsReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Reservoirs    []*ReservoirInfo       `protobuf:"bytes,1,rep,name=reservoirs,proto3" json:"reservoirs,omitempty"` // 使用 ReservoirInfo
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListReservoirsReply) Reset() {
	*x = ListReservoirsReply{}
	mi := &file_api_mapdata_v1_mapdata_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListReservoirsReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListReservoirsReply) ProtoMessage() {}

func (x *ListReservoirsReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_mapdata_v1_mapdata_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListReservoirsReply.ProtoReflect.Descriptor instead.
func (*ListReservoirsReply) Descriptor() ([]byte, []int) {
	return file_api_mapdata_v1_mapdata_proto_rawDescGZIP(), []int{6}
}

func (x *ListReservoirsReply) GetReservoirs() []*ReservoirInfo {
	if x != nil {
		return x.Reservoirs
	}
	return nil
}

// --- GenerateCurves 相关消息 ---
type GenerateCurvesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ReservoirId   string                 `protobuf:"bytes,1,opt,name=reservoir_id,json=reservoirId,proto3" json:"reservoir_id,omitempty"` // 水库 ID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenerateCurvesRequest) Reset() {
	*x = GenerateCurvesRequest{}
	mi := &file_api_mapdata_v1_mapdata_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateCurvesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateCurvesRequest) ProtoMessage() {}

func (x *GenerateCurvesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_mapdata_v1_mapdata_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateCurvesRequest.ProtoReflect.Descriptor instead.
func (*GenerateCurvesRequest) Descriptor() ([]byte, []int) {
	return file_api_mapdata_v1_mapdata_proto_rawDescGZIP(), []int{7}
}

func (x *GenerateCurvesRequest) GetReservoirId() string {
	if x != nil {
		return x.ReservoirId
	}
	return ""
}

type GenerateCurvesReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"` // 成功或失败的消息
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenerateCurvesReply) Reset() {
	*x = GenerateCurvesReply{}
	mi := &file_api_mapdata_v1_mapdata_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateCurvesReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateCurvesReply) ProtoMessage() {}

func (x *GenerateCurvesReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_mapdata_v1_mapdata_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateCurvesReply.ProtoReflect.Descriptor instead.
func (*GenerateCurvesReply) Descriptor() ([]byte, []int) {
	return file_api_mapdata_v1_mapdata_proto_rawDescGZIP(), []int{8}
}

func (x *GenerateCurvesReply) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// --- GetCurves 相关消息 ---
type GetCurvesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ReservoirId   string                 `protobuf:"bytes,1,opt,name=reservoir_id,json=reservoirId,proto3" json:"reservoir_id,omitempty"` // 水库 ID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCurvesRequest) Reset() {
	*x = GetCurvesRequest{}
	mi := &file_api_mapdata_v1_mapdata_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCurvesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCurvesRequest) ProtoMessage() {}

func (x *GetCurvesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_mapdata_v1_mapdata_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCurvesRequest.ProtoReflect.Descriptor instead.
func (*GetCurvesRequest) Descriptor() ([]byte, []int) {
	return file_api_mapdata_v1_mapdata_proto_rawDescGZIP(), []int{9}
}

func (x *GetCurvesRequest) GetReservoirId() string {
	if x != nil {
		return x.ReservoirId
	}
	return ""
}

type GetCurvesReply struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	StorageCurve   []*CurvePoint          `protobuf:"bytes,1,rep,name=storage_curve,json=storageCurve,proto3" json:"storage_curve,omitempty"`
	DischargeCurve []*CurvePoint          `protobuf:"bytes,2,rep,name=discharge_curve,json=dischargeCurve,proto3" json:"discharge_curve,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetCurvesReply) Reset() {
	*x = GetCurvesReply{}
	mi := &file_api_mapdata_v1_mapdata_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCurvesReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCurvesReply) ProtoMessage() {}

func (x *GetCurvesReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_mapdata_v1_mapdata_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCurvesReply.ProtoReflect.Descriptor instead.
func (*GetCurvesReply) Descriptor() ([]byte, []int) {
	return file_api_mapdata_v1_mapdata_proto_rawDescGZIP(), []int{10}
}

func (x *GetCurvesReply) GetStorageCurve() []*CurvePoint {
	if x != nil {
		return x.StorageCurve
	}
	return nil
}

func (x *GetCurvesReply) GetDischargeCurve() []*CurvePoint {
	if x != nil {
		return x.DischargeCurve
	}
	return nil
}

// --- UpdateCurves 相关消息 ---
type UpdateCurvesRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ReservoirId    string                 `protobuf:"bytes,1,opt,name=reservoir_id,json=reservoirId,proto3" json:"reservoir_id,omitempty"` // 水库 ID
	StorageCurve   []*CurvePoint          `protobuf:"bytes,2,rep,name=storage_curve,json=storageCurve,proto3" json:"storage_curve,omitempty"`
	DischargeCurve []*CurvePoint          `protobuf:"bytes,3,rep,name=discharge_curve,json=dischargeCurve,proto3" json:"discharge_curve,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *UpdateCurvesRequest) Reset() {
	*x = UpdateCurvesRequest{}
	mi := &file_api_mapdata_v1_mapdata_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateCurvesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateCurvesRequest) ProtoMessage() {}

func (x *UpdateCurvesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_mapdata_v1_mapdata_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateCurvesRequest.ProtoReflect.Descriptor instead.
func (*UpdateCurvesRequest) Descriptor() ([]byte, []int) {
	return file_api_mapdata_v1_mapdata_proto_rawDescGZIP(), []int{11}
}

func (x *UpdateCurvesRequest) GetReservoirId() string {
	if x != nil {
		return x.ReservoirId
	}
	return ""
}

func (x *UpdateCurvesRequest) GetStorageCurve() []*CurvePoint {
	if x != nil {
		return x.StorageCurve
	}
	return nil
}

func (x *UpdateCurvesRequest) GetDischargeCurve() []*CurvePoint {
	if x != nil {
		return x.DischargeCurve
	}
	return nil
}

type UpdateCurvesReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"` // 成功或失败的消息
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateCurvesReply) Reset() {
	*x = UpdateCurvesReply{}
	mi := &file_api_mapdata_v1_mapdata_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateCurvesReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateCurvesReply) ProtoMessage() {}

func (x *UpdateCurvesReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_mapdata_v1_mapdata_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateCurvesReply.ProtoReflect.Descriptor instead.
func (*UpdateCurvesReply) Descriptor() ([]byte, []int) {
	return file_api_mapdata_v1_mapdata_proto_rawDescGZIP(), []int{12}
}

func (x *UpdateCurvesReply) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_api_mapdata_v1_mapdata_proto protoreflect.FileDescriptor

const file_api_mapdata_v1_mapdata_proto_rawDesc = "" +
	"\n" +
	"\x1capi/mapdata/v1/mapdata.proto\x12\n" +
	"mapdata.v1\x1a\x1cgoogle/api/annotations.proto\x1a\x1egoogle/protobuf/wrappers.proto\"f\n" +
	"\n" +
	"CurvePoint\x12\x14\n" +
	"\x05level\x18\x01 \x01(\x01R\x05level\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x01R\x05value\x12,\n" +
	"\x02id\x18\x03 \x01(\v2\x1c.google.protobuf.UInt64ValueR\x02id\"\x89\x01\n" +
	"\tBasinInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x1d\n" +
	"\n" +
	"basin_name\x18\x02 \x01(\tR\tbasinName\x12!\n" +
	"\fcontrol_area\x18\x03 \x01(\x01R\vcontrolArea\x12*\n" +
	"\x11main_stream_slope\x18\x04 \x01(\x01R\x0fmainStreamSlope\"\xa8\x01\n" +
	"\rReservoirInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1a\n" +
	"\blatitude\x18\x03 \x01(\x01R\blatitude\x12\x1c\n" +
	"\tlongitude\x18\x04 \x01(\x01R\tlongitude\x12!\n" +
	"\fcontrol_area\x18\x05 \x01(\x01R\vcontrolArea\x12\x16\n" +
	"\x06weight\x18\x06 \x01(\x01R\x06weight\"\x13\n" +
	"\x11ListBasinsRequest\"@\n" +
	"\x0fListBasinsReply\x12-\n" +
	"\x06basins\x18\x01 \x03(\v2\x15.mapdata.v1.BasinInfoR\x06basins\"\x17\n" +
	"\x15ListReservoirsRequest\"P\n" +
	"\x13ListReservoirsReply\x129\n" +
	"\n" +
	"reservoirs\x18\x01 \x03(\v2\x19.mapdata.v1.ReservoirInfoR\n" +
	"reservoirs\":\n" +
	"\x15GenerateCurvesRequest\x12!\n" +
	"\freservoir_id\x18\x01 \x01(\tR\vreservoirId\"/\n" +
	"\x13GenerateCurvesReply\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"5\n" +
	"\x10GetCurvesRequest\x12!\n" +
	"\freservoir_id\x18\x01 \x01(\tR\vreservoirId\"\x8e\x01\n" +
	"\x0eGetCurvesReply\x12;\n" +
	"\rstorage_curve\x18\x01 \x03(\v2\x16.mapdata.v1.CurvePointR\fstorageCurve\x12?\n" +
	"\x0fdischarge_curve\x18\x02 \x03(\v2\x16.mapdata.v1.CurvePointR\x0edischargeCurve\"\xb6\x01\n" +
	"\x13UpdateCurvesRequest\x12!\n" +
	"\freservoir_id\x18\x01 \x01(\tR\vreservoirId\x12;\n" +
	"\rstorage_curve\x18\x02 \x03(\v2\x16.mapdata.v1.CurvePointR\fstorageCurve\x12?\n" +
	"\x0fdischarge_curve\x18\x03 \x03(\v2\x16.mapdata.v1.CurvePointR\x0edischargeCurve\"-\n" +
	"\x11UpdateCurvesReply\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage2\xe4\x04\n" +
	"\aMapData\x12`\n" +
	"\n" +
	"ListBasins\x12\x1d.mapdata.v1.ListBasinsRequest\x1a\x1b.mapdata.v1.ListBasinsReply\"\x16\x82\xd3\xe4\x93\x02\x10\x12\x0e/v1/map/basins\x12p\n" +
	"\x0eListReservoirs\x12!.mapdata.v1.ListReservoirsRequest\x1a\x1f.mapdata.v1.ListReservoirsReply\"\x1a\x82\xd3\xe4\x93\x02\x14\x12\x12/v1/map/reservoirs\x12\x8e\x01\n" +
	"\x0eGenerateCurves\x12!.mapdata.v1.GenerateCurvesRequest\x1a\x1f.mapdata.v1.GenerateCurvesReply\"8\x82\xd3\xe4\x93\x022:\x01*\"-/v1/reservoirs/{reservoir_id}/generate-curves\x12s\n" +
	"\tGetCurves\x12\x1c.mapdata.v1.GetCurvesRequest\x1a\x1a.mapdata.v1.GetCurvesReply\",\x82\xd3\xe4\x93\x02&\x12$/v1/reservoirs/{reservoir_id}/curves\x12\x7f\n" +
	"\fUpdateCurves\x12\x1f.mapdata.v1.UpdateCurvesRequest\x1a\x1d.mapdata.v1.UpdateCurvesReply\"/\x82\xd3\xe4\x93\x02):\x01*\x1a$/v1/reservoirs/{reservoir_id}/curvesB>\n" +
	"\x0eapi.mapdata.v1P\x01Z*ReservoirFloodPrediction/api/mapdata/v1;v1b\x06proto3"

var (
	file_api_mapdata_v1_mapdata_proto_rawDescOnce sync.Once
	file_api_mapdata_v1_mapdata_proto_rawDescData []byte
)

func file_api_mapdata_v1_mapdata_proto_rawDescGZIP() []byte {
	file_api_mapdata_v1_mapdata_proto_rawDescOnce.Do(func() {
		file_api_mapdata_v1_mapdata_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_mapdata_v1_mapdata_proto_rawDesc), len(file_api_mapdata_v1_mapdata_proto_rawDesc)))
	})
	return file_api_mapdata_v1_mapdata_proto_rawDescData
}

var file_api_mapdata_v1_mapdata_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_api_mapdata_v1_mapdata_proto_goTypes = []any{
	(*CurvePoint)(nil),             // 0: mapdata.v1.CurvePoint
	(*BasinInfo)(nil),              // 1: mapdata.v1.BasinInfo
	(*ReservoirInfo)(nil),          // 2: mapdata.v1.ReservoirInfo
	(*ListBasinsRequest)(nil),      // 3: mapdata.v1.ListBasinsRequest
	(*ListBasinsReply)(nil),        // 4: mapdata.v1.ListBasinsReply
	(*ListReservoirsRequest)(nil),  // 5: mapdata.v1.ListReservoirsRequest
	(*ListReservoirsReply)(nil),    // 6: mapdata.v1.ListReservoirsReply
	(*GenerateCurvesRequest)(nil),  // 7: mapdata.v1.GenerateCurvesRequest
	(*GenerateCurvesReply)(nil),    // 8: mapdata.v1.GenerateCurvesReply
	(*GetCurvesRequest)(nil),       // 9: mapdata.v1.GetCurvesRequest
	(*GetCurvesReply)(nil),         // 10: mapdata.v1.GetCurvesReply
	(*UpdateCurvesRequest)(nil),    // 11: mapdata.v1.UpdateCurvesRequest
	(*UpdateCurvesReply)(nil),      // 12: mapdata.v1.UpdateCurvesReply
	(*wrapperspb.UInt64Value)(nil), // 13: google.protobuf.UInt64Value
}
var file_api_mapdata_v1_mapdata_proto_depIdxs = []int32{
	13, // 0: mapdata.v1.CurvePoint.id:type_name -> google.protobuf.UInt64Value
	1,  // 1: mapdata.v1.ListBasinsReply.basins:type_name -> mapdata.v1.BasinInfo
	2,  // 2: mapdata.v1.ListReservoirsReply.reservoirs:type_name -> mapdata.v1.ReservoirInfo
	0,  // 3: mapdata.v1.GetCurvesReply.storage_curve:type_name -> mapdata.v1.CurvePoint
	0,  // 4: mapdata.v1.GetCurvesReply.discharge_curve:type_name -> mapdata.v1.CurvePoint
	0,  // 5: mapdata.v1.UpdateCurvesRequest.storage_curve:type_name -> mapdata.v1.CurvePoint
	0,  // 6: mapdata.v1.UpdateCurvesRequest.discharge_curve:type_name -> mapdata.v1.CurvePoint
	3,  // 7: mapdata.v1.MapData.ListBasins:input_type -> mapdata.v1.ListBasinsRequest
	5,  // 8: mapdata.v1.MapData.ListReservoirs:input_type -> mapdata.v1.ListReservoirsRequest
	7,  // 9: mapdata.v1.MapData.GenerateCurves:input_type -> mapdata.v1.GenerateCurvesRequest
	9,  // 10: mapdata.v1.MapData.GetCurves:input_type -> mapdata.v1.GetCurvesRequest
	11, // 11: mapdata.v1.MapData.UpdateCurves:input_type -> mapdata.v1.UpdateCurvesRequest
	4,  // 12: mapdata.v1.MapData.ListBasins:output_type -> mapdata.v1.ListBasinsReply
	6,  // 13: mapdata.v1.MapData.ListReservoirs:output_type -> mapdata.v1.ListReservoirsReply
	8,  // 14: mapdata.v1.MapData.GenerateCurves:output_type -> mapdata.v1.GenerateCurvesReply
	10, // 15: mapdata.v1.MapData.GetCurves:output_type -> mapdata.v1.GetCurvesReply
	12, // 16: mapdata.v1.MapData.UpdateCurves:output_type -> mapdata.v1.UpdateCurvesReply
	12, // [12:17] is the sub-list for method output_type
	7,  // [7:12] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_api_mapdata_v1_mapdata_proto_init() }
func file_api_mapdata_v1_mapdata_proto_init() {
	if File_api_mapdata_v1_mapdata_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_mapdata_v1_mapdata_proto_rawDesc), len(file_api_mapdata_v1_mapdata_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_mapdata_v1_mapdata_proto_goTypes,
		DependencyIndexes: file_api_mapdata_v1_mapdata_proto_depIdxs,
		MessageInfos:      file_api_mapdata_v1_mapdata_proto_msgTypes,
	}.Build()
	File_api_mapdata_v1_mapdata_proto = out.File
	file_api_mapdata_v1_mapdata_proto_goTypes = nil
	file_api_mapdata_v1_mapdata_proto_depIdxs = nil
}
